apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: omniscope-kv-sync
  namespace: omniscope
spec:
  provider: azure
  secretObjects:
    - secretName: omniscope-kv-secrets
      type: Opaque
      data:
        - objectName: __KEYVAULT_SECRET_NAME__
          key: __KEYVAULT_SECRET_NAME__
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ""
    keyvaultName: "__KEYVAULT_NAME__"
    cloudName: ""
    tenantId: "__TENANT_ID__"
    objects: |
      array:
        - |
          objectName: __KEYVAULT_SECRET_NAME__
          objectType: secret
